server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://www.quilljou.com:3306/ofo-battery?useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: ofotest
  aop:
    proxy-target-class: true
mybatis:
  type-aliases-package: cn.senninha.db.entity
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml






