server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://119.28.84.111:3306/ofo-battery?useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: ofotest

mybatis:
  type-aliases-package: cn.senninha.db.entity
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml





