server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ofo-battery?useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:
  messages:
    encoding: UTF-8




