

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306
    username: root
    password:
    name: ofo
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:db/mapper/*.xml
  type-aliases-package: com.winter.model

server:
  port: 8080

